project:
  type: website
  output-dir: docs

website:
  title: "Integrandes"
  favicon: images/logo.png
  open-graph: true
  site-url: https://integrandesconsulting.github.io/
  navbar:
    logo: images/logo.png
    collapse-level: 1
    right:
      - href: index.qmd
        text: Inicio
      - href: servicios.qmd
        text: Servicios
      - href: portafolio.qmd
        text: Portafolio
      - href: equipo.qmd
        text: Equipo
      - href: contacto.qmd
        text: Contacto
  page-footer:
    border: true
    center:
      - icon: github
        href: https://github.com/integrandesconsulting
      - icon: facebook
        href: https://www.facebook.com/integrandes.co
      - icon: youtube
        href: https://www.youtube.com/
    right: "Copyright Â© 2026 R.R."

format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right

editor: visual
